### ISSUE TITLE
server panic

### ISSUE THREAD

**Issue by futurist** [goproxy/goproxy#40] opened 2022-12-16 08:50 UTC
sometimes the server log a panic:

```
http: panic serving 127.0.0.1:26140: runtime error: invalid memory address or nil pointer dereference
goroutine 55 [running]:
net/http.(*conn).serve.func1()
        /root/.gobrew/current/go/src/net/http/server.go:1850 +0xbf
panic({0x813680, 0xbae0d0})
        /root/.gobrew/current/go/src/runtime/panic.go:890 +0x262
log.(*Logger).Output(0xc0001620f0, 0x2?, {0xc0002440c0, 0x54})
        /root/.gobrew/current/go/src/log/log.go:198 +0x356
github.com/goproxy/goproxy.(*Goproxy).logErrorf(0xc0001a4000, {0x884d63?, 0xc00021a300?}, {0xc0001419d8?, 0xc000212300?, 0xc0002161e0?})
        /root/go/pkg/mod/github.com/goproxy/goproxy@v0.11.0/goproxy.go:734 +0xac
github.com/goproxy/goproxy.(*Goproxy).ServeHTTP(0xc0001a4000, {0x9358a0?, 0xc000220380}, 0xc00023a400)
        /root/go/pkg/mod/github.com/goproxy/goproxy@v0.11.0/goproxy.go:560 +0x1b66
net/http.serverHandler.ServeHTTP({0xc000214330?}, {0x9358a0, 0xc000220380}, 0xc00023a400)
        /root/.gobrew/current/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0002420a0, {0x935d60, 0xc00011b890})
        /root/.gobrew/current/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /root/.gobrew/current/go/src/net/http/server.go:3102 +0x4db
```

what is the cause? can it be ignored?

**Comment by aofei** [comment] 2022-12-16 09:05
The code at `/root/go/pkg/mod/github.com/goproxy/goproxy@v0.11.0/goproxy.go:734` is actually nil checked:

https://github.com/goproxy/goproxy/blob/27501d9c0f711c562a65ff3fbf8179a339ef1c0f/goproxy.go#L733-L734

Based on the code at `/root/.gobrew/current/go/src/log/log.go:198`, it looks like your `Goproxy.ErrorLogger.out` is incorrectly set to `nil`, which shouldn't normally happen. How is your `Goproxy.ErrorLogger` configured?

**Comment by aofei** [comment] 2022-12-20 07:04
Closing this issue, since this panic is not caused by any bug in Goproxy.

**Closed by aofei** 2022-12-20 07:04 UTC
